### ISSUE TITLE
Broken?

### ISSUE THREAD

**Issue by luke-** [humhub/humhub-modules-drawio#10]
Seems its not longer working with the latest drawio webapp.

@yurabakhtin Can you check if we can migrate the module? Otherwise we should mark the module as deprecated.

**Comment by yurabakhtin** [comment]
@luke- Please tell me what you mean with "the latest drawio webapp", because for me it looks correctly:

<img width="1058" alt="test_drawio" src="https://user-images.githubusercontent.com/6995524/114828641-d52b2680-9dd2-11eb-841d-f4745f72a2bb.png">

**Comment by luke-** [comment]
One point is the default url, which need to be changed:
![image](https://user-images.githubusercontent.com/4736168/114834602-ff7be480-9dd0-11eb-83fa-1c85906508f6.png)

Can you create a draw io image, save and reopen it?

**Comment by yurabakhtin** [comment]
@luke- 

> Can you create a draw io image, save and reopen it?

Yes, I can do this with server https://embed.diagrams.net:

<img width="1195" alt="test_new_server" src="https://user-images.githubusercontent.com/6995524/114863782-dec78500-9df8-11eb-91f4-382661f5d10c.png">

> One point is the default url, which need to be changed:

Ok, I changed the default URL to new in PR https://github.com/humhub-contrib/drawio/pull/11.

**Comment by luke-** [comment]
@yurabakhtin Thanks!

**Comment by TorstenS73** [comment]
It seems a minor issue came up with this fix:

![image](https://user-images.githubusercontent.com/7091889/123777649-b5cf7000-d8d0-11eb-8b2c-43d7be06c9e4.png)

Not a big thing, but misleading at least. I was tempted to add the Url to the URL.

**Comment by yurabakhtin** [comment]
@TorstenS73 Yes, my bad, thank you for the reporting this.

@luke- Fixed in PR https://github.com/humhub-contrib/drawio/pull/13.
