### ISSUE TITLE
Drawings are always 0 bytes

### ISSUE THREAD

**Issue by TorstenS73** [humhub/humhub-modules-drawio#12]
![image](https://user-images.githubusercontent.com/7091889/123778651-9a189980-d8d1-11eb-9d13-92da2326d8e7.png)

Actually, the drawing is *not emtpy* in this case.

It's not very large, but if I understand B as in "Bytes", this looks like it was a broken file, which it isn't.

Even if this was meant to be kilobytes, anything which is not empty should get rounded up to 1 KB IMHO.

**Comment by yurabakhtin** [comment]
@TorstenS73 @luke- Fixed in PR https://github.com/humhub-contrib/drawio/pull/14, but each drawio file should be resaved in order to see file size.

<img width="663" alt="drawio_file_size" src="https://user-images.githubusercontent.com/6995524/123961271-d672f500-d9b8-11eb-915a-64e34786d7af.png">

**Comment by luke-** [comment]
@yurabakhtin thanks!
