### ISSUE TITLE
Nonce support is missing in \drawio\views\open\index.php

### ISSUE THREAD

**Issue by aronbos** [humhub/humhub-modules-drawio#8]
Drawio can not be loaded as de nonce code is missing.

**Comment by yurabakhtin** [comment]
@luke- I have installed this module and can create a digram, but I don't know what "Nonce" means, please tell me where and I should test, thanks.

**Comment by luke-** [comment]
@yurabakhtin There must be an added nonce attribute to all inline `<script nonce...>` script tags. You can either start the tag via `Html::script`  or add <script < ?= Html::nonce() ? >....

**Comment by yurabakhtin** [comment]
@luke- Thank you for the info. PR https://github.com/humhub-contrib/drawio/pull/9.
